services:
  app:
    image: "ghcr.io/wkf2000/lennyverse:latest"
    container_name: lennyverse
    restart: unless-stopped
    networks:
      - 1panel-network      
    ports:
      - "8511:8000"
      - "8512:8001"
    environment:
      - TZ=America/Los_Angeles
    env_file:
      - .env

networks:
  1panel-network:
    external: true